# Generated by Django 4.2.15 on 2024-08-18 02:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commander',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('color_identities', models.CharField(max_length=5)),
                ('image', models.URLField()),
                ('scryfall_uri', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('index', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('number_of_turns', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('first_knockout_turn', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('minutes', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('favorite_commander', models.UUIDField(blank=True, default=None, null=True)),
                ('moxfield_id', models.CharField(blank=True, max_length=50, null=True)),
                ('archidekt_id', models.CharField(blank=True, max_length=50, null=True)),
                ('toski_id', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MatchPlayer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('rank', models.PositiveSmallIntegerField()),
                ('turn_position', models.PositiveSmallIntegerField()),
                ('commanders', models.ManyToManyField(to='matches.commander')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_players', to='matches.match')),
            ],
        ),
    ]
