# Generated by Django 4.2.15 on 2024-08-17 03:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_remove_profile_user_id_profile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commander',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('color_identities', models.CharField(max_length=5)),
                ('image', models.URLField()),
                ('scryfall_uri', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('number_of_turns', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('first_knockout_turn', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('minutes', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MatchPlayer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('turn_position', models.PositiveSmallIntegerField()),
                ('commanders', models.ManyToManyField(to='profiles.commander')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.match')),
            ],
        ),
    ]
