# Generated by Django 4.2.15 on 2024-08-15 20:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=18)),
                ('favorite_commander', models.UUIDField()),
                ('moxfield_id', models.CharField(max_length=50)),
                ('archidektId', models.CharField(max_length=50)),
                ('toski_id', models.CharField(max_length=50)),
            ],
        ),
    ]
