# Generated by Django 4.2.15 on 2024-08-15 21:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=18)),
                ('favorite_commander', models.UUIDField(blank=True, default=None, null=True)),
                ('moxfield_id', models.CharField(blank=True, max_length=50, null=True)),
                ('archidekt_id', models.CharField(blank=True, max_length=50, null=True)),
                ('toski_id', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
