# Generated by Django 4.2.15 on 2024-08-15 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='archidektId',
            new_name='archidekt_id',
        ),
    ]
