services:
  db:
    image: postgres
    container_name: postgresql
    hostname: postgresql
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "4444:4444"

volumes:
  postgres_data:
