services:
  db:
    build: ./docker/db
    image: postgres
    container_name: arcanis_db
    hostname: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 4444:5432
  server:
    build: ./docker/server
    image: python
    container_name: arcanis_server
    hostname: server
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      SECRET_KEY: ${SECRET_KEY}
      ENV: ${ENV}
    ports:
      - 8000:8000
volumes:
  postgres_data:
    name: arcanis_db_vol
