services:
  db:
    build: ./docker/db
    container_name: arcanis_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
  server:
    build: 
      dockerfile: ./docker/server/Dockerfile.prod
      context: .
    command: gunicorn arcanis.wsgi:application --bind 0.0.0.0:8000
    container_name: arcanis_server
    volumes:
      - ./app/:/usr/src/app/
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      SECRET_KEY: ${SECRET_KEY}
      ENV: ${ENV}
      DEBUG: ${DEBUG}
    ports:
      - 8000:8000
    depends_on:
      - db
volumes:
  postgres_data:
    name: arcanis_db_vol
