# Generated by Django 4.2.15 on 2024-08-19 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commander',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('color_identities', models.CharField(max_length=5)),
                ('image', models.URLField()),
                ('scryfall_uri', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('index', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('number_of_turns', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('first_knockout_turn', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('minutes', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Playgroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=15)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='playgroups_created', to='playgroups.profile')),
                ('managers', models.ManyToManyField(related_name='playgroups_managed', to='playgroups.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('playgroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='playgroups.playgroup')),
            ],
            options={
                'unique_together': {('playgroup', 'name')},
            },
        ),
        migrations.CreateModel(
            name='MatchPlayer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rank', models.PositiveSmallIntegerField()),
                ('turn_position', models.PositiveSmallIntegerField()),
                ('commanders', models.ManyToManyField(to='playgroups.commander')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_players', to='playgroups.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_players', to='playgroups.player')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='playgroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='playgroups.playgroup'),
        ),
        migrations.AlterUniqueTogether(
            name='match',
            unique_together={('playgroup', 'index')},
        ),
    ]
