# Generated by Django 4.2.15 on 2024-08-18 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playgroups', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='match',
            unique_together={('playgroup', 'index')},
        ),
        migrations.AlterUniqueTogether(
            name='player',
            unique_together={('playgroup', 'name')},
        ),
    ]
