# Generated by Django 4.2.15 on 2024-08-21 18:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("playgroups", "0002_alter_playgroup_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playgroup",
            name="managers",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="playgroups_managed",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="playgroup",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                default="b6dbeaf3-ecd7-4872-93c3-3e93544ea76f",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="playgroups_owned",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
