# Generated by Django 4.2.15 on 2024-08-22 00:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("playgroups", "0003_alter_playgroup_managers_alter_playgroup_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playgroup",
            name="managers",
            field=models.ManyToManyField(
                blank=True,
                related_name="playgroups_managed",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
