# Generated by Django 4.2.15 on 2024-08-23 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("playgroups", "0004_alter_playgroup_managers"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="match",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="matchplayer",
            name="player",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="match_players",
                to="playgroups.player",
            ),
        ),
        migrations.RemoveField(
            model_name="match",
            name="index",
        ),
    ]
