# Generated by Django 4.2.15 on 2024-08-23 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "playgroups",
            "0005_alter_match_unique_together_alter_matchplayer_player_and_more",
        ),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="matchplayer",
            unique_together={("match", "rank"), ("match", "turn_position")},
        ),
    ]
